include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    deprecated_member_use: ignore
    invalid_use_of_internal_member: ignore
    curly_braces_in_flow_control_structures: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    curly_braces_in_flow_control_structures: false
