include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Tratar como info (no bloquean CI) — se corregirán iterativamente
    prefer_const_constructors: info
    prefer_const_literals_to_create_immutables: info
    deprecated_member_use: info
    invalid_use_of_internal_member: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
