default_platform(:ios)

platform :ios do

  desc "Sincronizar certificados con Match"
  lane :sync_certs do
    match(
      type: "appstore",
      app_identifier: "app.rosports.mobile",
      readonly: is_ci
    )
  end

  desc "Build y subir a TestFlight (beta)"
  lane :beta do
    sync_certs

    increment_build_number(
      xcodeproj: "Runner.xcodeproj",
      build_number: ENV["GITHUB_RUN_NUMBER"] || Time.now.to_i.to_s
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "app.rosports.mobile" => "match AppStore app.rosports.mobile"
        }
      }
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: "fastlane/api_key.json"
    )
  end

  desc "Subir a producción App Store"
  lane :release do
    sync_certs
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release"
    )
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: false,
      force: true
    )
  end
end
